const countries = [
  {
    id: 0,
    rewrite: "",
    baslik: "",
    alankodu: "",
  },
  {
    id: 1,
    rewrite: "AF",
    baslik: "Afghanistan",
    alankodu: "93",
  },
  {
    id: 2,
    rewrite: "AL",
    baslik: "Albania",
    alankodu: "355",
  },
  {
    id: 3,
    rewrite: "DZ",
    baslik: "Algeria",
    alankodu: "213",
  },
  {
    id: 4,
    rewrite: "AS",
    baslik: "American Samoa",
    alankodu: "1684",
  },
  {
    id: 5,
    rewrite: "AD",
    baslik: "Andorra",
    alankodu: "376",
  },
  {
    id: 6,
    rewrite: "AO",
    baslik: "Angola",
    alankodu: "244",
  },
  {
    id: 7,
    rewrite: "AI",
    baslik: "Anguilla",
    alankodu: "1264",
  },
  {
    id: 8,
    rewrite: "AQ",
    baslik: "Antarctica",
    alankodu: "0",
  },
  {
    id: 9,
    rewrite: "AG",
    baslik: "Antigua And Barbuda",
    alankodu: "1268",
  },
  {
    id: 10,
    rewrite: "AR",
    baslik: "Argentina",
    alankodu: "54",
  },
  {
    id: 11,
    rewrite: "AM",
    baslik: "Armenia",
    alankodu: "374",
  },
  {
    id: 12,
    rewrite: "AW",
    baslik: "Aruba",
    alankodu: "297",
  },
  {
    id: 13,
    rewrite: "AU",
    baslik: "Australia",
    alankodu: "61",
  },
  {
    id: 14,
    rewrite: "AT",
    baslik: "Austria",
    alankodu: "43",
  },
  {
    id: 15,
    rewrite: "AZ",
    baslik: "Azerbaijan",
    alankodu: "994",
  },
  {
    id: 16,
    rewrite: "BS",
    baslik: "Bahamas The",
    alankodu: "1242",
  },
  {
    id: 17,
    rewrite: "BH",
    baslik: "Bahrain",
    alankodu: "973",
  },
  {
    id: 18,
    rewrite: "BD",
    baslik: "Bangladesh",
    alankodu: "880",
  },
  {
    id: 19,
    rewrite: "BB",
    baslik: "Barbados",
    alankodu: "1246",
  },
  {
    id: 20,
    rewrite: "BY",
    baslik: "Belarus",
    alankodu: "375",
  },
  {
    id: 21,
    rewrite: "BE",
    baslik: "Belgium",
    alankodu: "32",
  },
  {
    id: 22,
    rewrite: "BZ",
    baslik: "Belize",
    alankodu: "501",
  },
  {
    id: 23,
    rewrite: "BJ",
    baslik: "Benin",
    alankodu: "229",
  },
  {
    id: 24,
    rewrite: "BM",
    baslik: "Bermuda",
    alankodu: "1441",
  },
  {
    id: 25,
    rewrite: "BT",
    baslik: "Bhutan",
    alankodu: "975",
  },
  {
    id: 26,
    rewrite: "BO",
    baslik: "Bolivia",
    alankodu: "591",
  },
  {
    id: 27,
    rewrite: "BA",
    baslik: "Bosnia and Herzegovina",
    alankodu: "387",
  },
  {
    id: 28,
    rewrite: "BW",
    baslik: "Botswana",
    alankodu: "267",
  },
  {
    id: 29,
    rewrite: "BV",
    baslik: "Bouvet Island",
    alankodu: "0",
  },
  {
    id: 30,
    rewrite: "BR",
    baslik: "Brazil",
    alankodu: "55",
  },
  {
    id: 31,
    rewrite: "IO",
    baslik: "British Indian Ocean Territory",
    alankodu: "246",
  },
  {
    id: 32,
    rewrite: "BN",
    baslik: "Brunei",
    alankodu: "673",
  },
  {
    id: 33,
    rewrite: "BG",
    baslik: "Bulgaria",
    alankodu: "359",
  },
  {
    id: 34,
    rewrite: "BF",
    baslik: "Burkina Faso",
    alankodu: "226",
  },
  {
    id: 35,
    rewrite: "BI",
    baslik: "Burundi",
    alankodu: "257",
  },
  {
    id: 36,
    rewrite: "KH",
    baslik: "Cambodia",
    alankodu: "855",
  },
  {
    id: 37,
    rewrite: "CM",
    baslik: "Cameroon",
    alankodu: "237",
  },
  {
    id: 38,
    rewrite: "CA",
    baslik: "Canada",
    alankodu: "1",
  },
  {
    id: 39,
    rewrite: "CV",
    baslik: "Cape Verde",
    alankodu: "238",
  },
  {
    id: 40,
    rewrite: "KY",
    baslik: "Cayman Islands",
    alankodu: "1345",
  },
  {
    id: 41,
    rewrite: "CF",
    baslik: "Central African Republic",
    alankodu: "236",
  },
  {
    id: 42,
    rewrite: "TD",
    baslik: "Chad",
    alankodu: "235",
  },
  {
    id: 43,
    rewrite: "CL",
    baslik: "Chile",
    alankodu: "56",
  },
  {
    id: 44,
    rewrite: "CN",
    baslik: "China",
    alankodu: "86",
  },
  {
    id: 45,
    rewrite: "CX",
    baslik: "Christmas Island",
    alankodu: "61",
  },
  {
    id: 46,
    rewrite: "CC",
    baslik: "Cocos (Keeling) Islands",
    alankodu: "672",
  },
  {
    id: 47,
    rewrite: "CO",
    baslik: "Colombia",
    alankodu: "57",
  },
  {
    id: 48,
    rewrite: "KM",
    baslik: "Comoros",
    alankodu: "269",
  },
  {
    id: 49,
    rewrite: "CG",
    baslik: "Republic Of The Congo",
    alankodu: "242",
  },
  {
    id: 50,
    rewrite: "CD",
    baslik: "Democratic Republic Of The Congo",
    alankodu: "242",
  },
  {
    id: 51,
    rewrite: "CK",
    baslik: "Cook Islands",
    alankodu: "682",
  },
  {
    id: 52,
    rewrite: "CR",
    baslik: "Costa Rica",
    alankodu: "506",
  },
  {
    id: 53,
    rewrite: "CI",
    baslik: "Cote D'Ivoire (Ivory Coast)",
    alankodu: "225",
  },
  {
    id: 54,
    rewrite: "HR",
    baslik: "Croatia (Hrvatska)",
    alankodu: "385",
  },
  {
    id: 55,
    rewrite: "CU",
    baslik: "Cuba",
    alankodu: "53",
  },
  {
    id: 56,
    rewrite: "CY",
    baslik: "Cyprus",
    alankodu: "357",
  },
  {
    id: 57,
    rewrite: "CZ",
    baslik: "Czech Republic",
    alankodu: "420",
  },
  {
    id: 58,
    rewrite: "DK",
    baslik: "Denmark",
    alankodu: "45",
  },
  {
    id: 59,
    rewrite: "DJ",
    baslik: "Djibouti",
    alankodu: "253",
  },
  {
    id: 60,
    rewrite: "DM",
    baslik: "Dominica",
    alankodu: "1767",
  },
  {
    id: 61,
    rewrite: "DO",
    baslik: "Dominican Republic",
    alankodu: "1809",
  },
  {
    id: 62,
    rewrite: "TP",
    baslik: "East Timor",
    alankodu: "670",
  },
  {
    id: 63,
    rewrite: "EC",
    baslik: "Ecuador",
    alankodu: "593",
  },
  {
    id: 64,
    rewrite: "EG",
    baslik: "Egypt",
    alankodu: "20",
  },
  {
    id: 65,
    rewrite: "SV",
    baslik: "El Salvador",
    alankodu: "503",
  },
  {
    id: 66,
    rewrite: "GQ",
    baslik: "Equatorial Guinea",
    alankodu: "240",
  },
  {
    id: 67,
    rewrite: "ER",
    baslik: "Eritrea",
    alankodu: "291",
  },
  {
    id: 68,
    rewrite: "EE",
    baslik: "Estonia",
    alankodu: "372",
  },
  {
    id: 69,
    rewrite: "ET",
    baslik: "Ethiopia",
    alankodu: "251",
  },
  {
    id: 70,
    rewrite: "XA",
    baslik: "External Territories of Australia",
    alankodu: "61",
  },
  {
    id: 71,
    rewrite: "FK",
    baslik: "Falkland Islands",
    alankodu: "500",
  },
  {
    id: 72,
    rewrite: "FO",
    baslik: "Faroe Islands",
    alankodu: "298",
  },
  {
    id: 73,
    rewrite: "FJ",
    baslik: "Fiji Islands",
    alankodu: "679",
  },
  {
    id: 74,
    rewrite: "FI",
    baslik: "Finland",
    alankodu: "358",
  },
  {
    id: 75,
    rewrite: "FR",
    baslik: "France",
    alankodu: "33",
  },
  {
    id: 76,
    rewrite: "GF",
    baslik: "French Guiana",
    alankodu: "594",
  },
  {
    id: 77,
    rewrite: "PF",
    baslik: "French Polynesia",
    alankodu: "689",
  },
  {
    id: 78,
    rewrite: "TF",
    baslik: "French Southern Territories",
    alankodu: "0",
  },
  {
    id: 79,
    rewrite: "GA",
    baslik: "Gabon",
    alankodu: "241",
  },
  {
    id: 80,
    rewrite: "GM",
    baslik: "Gambia The",
    alankodu: "220",
  },
  {
    id: 81,
    rewrite: "GE",
    baslik: "Georgia",
    alankodu: "995",
  },
  {
    id: 82,
    rewrite: "DE",
    baslik: "Germany",
    alankodu: "49",
  },
  {
    id: 83,
    rewrite: "GH",
    baslik: "Ghana",
    alankodu: "233",
  },
  {
    id: 84,
    rewrite: "GI",
    baslik: "Gibraltar",
    alankodu: "350",
  },
  {
    id: 85,
    rewrite: "GR",
    baslik: "Greece",
    alankodu: "30",
  },
  {
    id: 86,
    rewrite: "GL",
    baslik: "Greenland",
    alankodu: "299",
  },
  {
    id: 87,
    rewrite: "GD",
    baslik: "Grenada",
    alankodu: "1473",
  },
  {
    id: 88,
    rewrite: "GP",
    baslik: "Guadeloupe",
    alankodu: "590",
  },
  {
    id: 89,
    rewrite: "GU",
    baslik: "Guam",
    alankodu: "1671",
  },
  {
    id: 90,
    rewrite: "GT",
    baslik: "Guatemala",
    alankodu: "502",
  },
  {
    id: 91,
    rewrite: "XU",
    baslik: "Guernsey and Alderney",
    alankodu: "44",
  },
  {
    id: 92,
    rewrite: "GN",
    baslik: "Guinea",
    alankodu: "224",
  },
  {
    id: 93,
    rewrite: "GW",
    baslik: "Guinea-Bissau",
    alankodu: "245",
  },
  {
    id: 94,
    rewrite: "GY",
    baslik: "Guyana",
    alankodu: "592",
  },
  {
    id: 95,
    rewrite: "HT",
    baslik: "Haiti",
    alankodu: "509",
  },
  {
    id: 96,
    rewrite: "HM",
    baslik: "Heard and McDonald Islands",
    alankodu: "0",
  },
  {
    id: 97,
    rewrite: "HN",
    baslik: "Honduras",
    alankodu: "504",
  },
  {
    id: 98,
    rewrite: "HK",
    baslik: "Hong Kong S.A.R.",
    alankodu: "852",
  },
  {
    id: 99,
    rewrite: "HU",
    baslik: "Hungary",
    alankodu: "36",
  },
  {
    id: 100,
    rewrite: "IS",
    baslik: "Iceland",
    alankodu: "354",
  },
  {
    id: 101,
    rewrite: "IN",
    baslik: "India",
    alankodu: "91",
  },
  {
    id: 102,
    rewrite: "ID",
    baslik: "Indonesia",
    alankodu: "62",
  },
  {
    id: 103,
    rewrite: "IR",
    baslik: "Iran",
    alankodu: "98",
  },
  {
    id: 104,
    rewrite: "IQ",
    baslik: "Iraq",
    alankodu: "964",
  },
  {
    id: 105,
    rewrite: "IE",
    baslik: "Ireland",
    alankodu: "353",
  },
  {
    id: 106,
    rewrite: "IL",
    baslik: "Israel",
    alankodu: "972",
  },
  {
    id: 107,
    rewrite: "IT",
    baslik: "Italy",
    alankodu: "39",
  },
  {
    id: 108,
    rewrite: "JM",
    baslik: "Jamaica",
    alankodu: "1876",
  },
  {
    id: 109,
    rewrite: "JP",
    baslik: "Japan",
    alankodu: "81",
  },
  {
    id: 110,
    rewrite: "XJ",
    baslik: "Jersey",
    alankodu: "44",
  },
  {
    id: 111,
    rewrite: "JO",
    baslik: "Jordan",
    alankodu: "962",
  },
  {
    id: 112,
    rewrite: "KZ",
    baslik: "Kazakhstan",
    alankodu: "7",
  },
  {
    id: 113,
    rewrite: "KE",
    baslik: "Kenya",
    alankodu: "254",
  },
  {
    id: 114,
    rewrite: "KI",
    baslik: "Kiribati",
    alankodu: "686",
  },
  {
    id: 115,
    rewrite: "KP",
    baslik: "Korea North",
    alankodu: "850",
  },
  {
    id: 116,
    rewrite: "KR",
    baslik: "Korea South",
    alankodu: "82",
  },
  {
    id: 117,
    rewrite: "KW",
    baslik: "Kuwait",
    alankodu: "965",
  },
  {
    id: 118,
    rewrite: "KG",
    baslik: "Kyrgyzstan",
    alankodu: "996",
  },
  {
    id: 119,
    rewrite: "LA",
    baslik: "Laos",
    alankodu: "856",
  },
  {
    id: 120,
    rewrite: "LV",
    baslik: "Latvia",
    alankodu: "371",
  },
  {
    id: 121,
    rewrite: "LB",
    baslik: "Lebanon",
    alankodu: "961",
  },
  {
    id: 122,
    rewrite: "LS",
    baslik: "Lesotho",
    alankodu: "266",
  },
  {
    id: 123,
    rewrite: "LR",
    baslik: "Liberia",
    alankodu: "231",
  },
  {
    id: 124,
    rewrite: "LY",
    baslik: "Libya",
    alankodu: "218",
  },
  {
    id: 125,
    rewrite: "LI",
    baslik: "Liechtenstein",
    alankodu: "423",
  },
  {
    id: 126,
    rewrite: "LT",
    baslik: "Lithuania",
    alankodu: "370",
  },
  {
    id: 127,
    rewrite: "LU",
    baslik: "Luxembourg",
    alankodu: "352",
  },
  {
    id: 128,
    rewrite: "MO",
    baslik: "Macau S.A.R.",
    alankodu: "853",
  },
  {
    id: 129,
    rewrite: "MK",
    baslik: "Macedonia",
    alankodu: "389",
  },
  {
    id: 130,
    rewrite: "MG",
    baslik: "Madagascar",
    alankodu: "261",
  },
  {
    id: 131,
    rewrite: "MW",
    baslik: "Malawi",
    alankodu: "265",
  },
  {
    id: 132,
    rewrite: "MY",
    baslik: "Malaysia",
    alankodu: "60",
  },
  {
    id: 133,
    rewrite: "MV",
    baslik: "Maldives",
    alankodu: "960",
  },
  {
    id: 134,
    rewrite: "ML",
    baslik: "Mali",
    alankodu: "223",
  },
  {
    id: 135,
    rewrite: "MT",
    baslik: "Malta",
    alankodu: "356",
  },
  {
    id: 136,
    rewrite: "XM",
    baslik: "Man (Isle of)",
    alankodu: "44",
  },
  {
    id: 137,
    rewrite: "MH",
    baslik: "Marshall Islands",
    alankodu: "692",
  },
  {
    id: 138,
    rewrite: "MQ",
    baslik: "Martinique",
    alankodu: "596",
  },
  {
    id: 139,
    rewrite: "MR",
    baslik: "Mauritania",
    alankodu: "222",
  },
  {
    id: 140,
    rewrite: "MU",
    baslik: "Mauritius",
    alankodu: "230",
  },
  {
    id: 141,
    rewrite: "YT",
    baslik: "Mayotte",
    alankodu: "269",
  },
  {
    id: 142,
    rewrite: "MX",
    baslik: "Mexico",
    alankodu: "52",
  },
  {
    id: 143,
    rewrite: "FM",
    baslik: "Micronesia",
    alankodu: "691",
  },
  {
    id: 144,
    rewrite: "MD",
    baslik: "Moldova",
    alankodu: "373",
  },
  {
    id: 145,
    rewrite: "MC",
    baslik: "Monaco",
    alankodu: "377",
  },
  {
    id: 146,
    rewrite: "MN",
    baslik: "Mongolia",
    alankodu: "976",
  },
  {
    id: 147,
    rewrite: "MS",
    baslik: "Montserrat",
    alankodu: "1664",
  },
  {
    id: 148,
    rewrite: "MA",
    baslik: "Morocco",
    alankodu: "212",
  },
  {
    id: 149,
    rewrite: "MZ",
    baslik: "Mozambique",
    alankodu: "258",
  },
  {
    id: 150,
    rewrite: "MM",
    baslik: "Myanmar",
    alankodu: "95",
  },
  {
    id: 151,
    rewrite: "NA",
    baslik: "Namibia",
    alankodu: "264",
  },
  {
    id: 152,
    rewrite: "NR",
    baslik: "Nauru",
    alankodu: "674",
  },
  {
    id: 153,
    rewrite: "NP",
    baslik: "Nepal",
    alankodu: "977",
  },
  {
    id: 154,
    rewrite: "AN",
    baslik: "Netherlands Antilles",
    alankodu: "599",
  },
  {
    id: 155,
    rewrite: "NL",
    baslik: "Netherlands The",
    alankodu: "31",
  },
  {
    id: 156,
    rewrite: "NC",
    baslik: "New Caledonia",
    alankodu: "687",
  },
  {
    id: 157,
    rewrite: "NZ",
    baslik: "New Zealand",
    alankodu: "64",
  },
  {
    id: 158,
    rewrite: "NI",
    baslik: "Nicaragua",
    alankodu: "505",
  },
  {
    id: 159,
    rewrite: "NE",
    baslik: "Niger",
    alankodu: "227",
  },
  {
    id: 160,
    rewrite: "NG",
    baslik: "Nigeria",
    alankodu: "234",
  },
  {
    id: 161,
    rewrite: "NU",
    baslik: "Niue",
    alankodu: "683",
  },
  {
    id: 162,
    rewrite: "NF",
    baslik: "Norfolk Island",
    alankodu: "672",
  },
  {
    id: 163,
    rewrite: "MP",
    baslik: "Northern Mariana Islands",
    alankodu: "1670",
  },
  {
    id: 164,
    rewrite: "NO",
    baslik: "Norway",
    alankodu: "47",
  },
  {
    id: 165,
    rewrite: "OM",
    baslik: "Oman",
    alankodu: "968",
  },
  {
    id: 166,
    rewrite: "PK",
    baslik: "Pakistan",
    alankodu: "92",
  },
  {
    id: 167,
    rewrite: "PW",
    baslik: "Palau",
    alankodu: "680",
  },
  {
    id: 168,
    rewrite: "PS",
    baslik: "Palestinian Territory Occupied",
    alankodu: "970",
  },
  {
    id: 169,
    rewrite: "PA",
    baslik: "Panama",
    alankodu: "507",
  },
  {
    id: 170,
    rewrite: "PG",
    baslik: "Papua new Guinea",
    alankodu: "675",
  },
  {
    id: 171,
    rewrite: "PY",
    baslik: "Paraguay",
    alankodu: "595",
  },
  {
    id: 172,
    rewrite: "PE",
    baslik: "Peru",
    alankodu: "51",
  },
  {
    id: 173,
    rewrite: "PH",
    baslik: "Philippines",
    alankodu: "63",
  },
  {
    id: 174,
    rewrite: "PN",
    baslik: "Pitcairn Island",
    alankodu: "0",
  },
  {
    id: 175,
    rewrite: "PL",
    baslik: "Poland",
    alankodu: "48",
  },
  {
    id: 176,
    rewrite: "PT",
    baslik: "Portugal",
    alankodu: "351",
  },
  {
    id: 177,
    rewrite: "PR",
    baslik: "Puerto Rico",
    alankodu: "1787",
  },
  {
    id: 178,
    rewrite: "QA",
    baslik: "Qatar",
    alankodu: "974",
  },
  {
    id: 179,
    rewrite: "RE",
    baslik: "Reunion",
    alankodu: "262",
  },
  {
    id: 180,
    rewrite: "RO",
    baslik: "Romania",
    alankodu: "40",
  },
  {
    id: 181,
    rewrite: "RU",
    baslik: "Russia",
    alankodu: "70",
  },
  {
    id: 182,
    rewrite: "RW",
    baslik: "Rwanda",
    alankodu: "250",
  },
  {
    id: 183,
    rewrite: "SH",
    baslik: "Saint Helena",
    alankodu: "290",
  },
  {
    id: 184,
    rewrite: "KN",
    baslik: "Saint Kitts And Nevis",
    alankodu: "1869",
  },
  {
    id: 185,
    rewrite: "LC",
    baslik: "Saint Lucia",
    alankodu: "1758",
  },
  {
    id: 186,
    rewrite: "PM",
    baslik: "Saint Pierre and Miquelon",
    alankodu: "508",
  },
  {
    id: 187,
    rewrite: "VC",
    baslik: "Saint Vincent And The Grenadines",
    alankodu: "1784",
  },
  {
    id: 188,
    rewrite: "WS",
    baslik: "Samoa",
    alankodu: "684",
  },
  {
    id: 189,
    rewrite: "SM",
    baslik: "San Marino",
    alankodu: "378",
  },
  {
    id: 190,
    rewrite: "ST",
    baslik: "Sao Tome and Principe",
    alankodu: "239",
  },
  {
    id: 191,
    rewrite: "SA",
    baslik: "Saudi Arabia",
    alankodu: "966",
  },
  {
    id: 192,
    rewrite: "SN",
    baslik: "Senegal",
    alankodu: "221",
  },
  {
    id: 193,
    rewrite: "RS",
    baslik: "Serbia",
    alankodu: "381",
  },
  {
    id: 194,
    rewrite: "SC",
    baslik: "Seychelles",
    alankodu: "248",
  },
  {
    id: 195,
    rewrite: "SL",
    baslik: "Sierra Leone",
    alankodu: "232",
  },
  {
    id: 196,
    rewrite: "SG",
    baslik: "Singapore",
    alankodu: "65",
  },
  {
    id: 197,
    rewrite: "SK",
    baslik: "Slovakia",
    alankodu: "421",
  },
  {
    id: 198,
    rewrite: "SI",
    baslik: "Slovenia",
    alankodu: "386",
  },
  {
    id: 199,
    rewrite: "XG",
    baslik: "Smaller Territories of the UK",
    alankodu: "44",
  },
  {
    id: 200,
    rewrite: "SB",
    baslik: "Solomon Islands",
    alankodu: "677",
  },
  {
    id: 201,
    rewrite: "SO",
    baslik: "Somalia",
    alankodu: "252",
  },
  {
    id: 202,
    rewrite: "ZA",
    baslik: "South Africa",
    alankodu: "27",
  },
  {
    id: 203,
    rewrite: "GS",
    baslik: "South Georgia",
    alankodu: "0",
  },
  {
    id: 204,
    rewrite: "SS",
    baslik: "South Sudan",
    alankodu: "211",
  },
  {
    id: 205,
    rewrite: "ES",
    baslik: "Spain",
    alankodu: "34",
  },
  {
    id: 206,
    rewrite: "LK",
    baslik: "Sri Lanka",
    alankodu: "94",
  },
  {
    id: 207,
    rewrite: "SD",
    baslik: "Sudan",
    alankodu: "249",
  },
  {
    id: 208,
    rewrite: "SR",
    baslik: "Suriname",
    alankodu: "597",
  },
  {
    id: 209,
    rewrite: "SJ",
    baslik: "Svalbard And Jan Mayen Islands",
    alankodu: "47",
  },
  {
    id: 210,
    rewrite: "SZ",
    baslik: "Swaziland",
    alankodu: "268",
  },
  {
    id: 211,
    rewrite: "SE",
    baslik: "Sweden",
    alankodu: "46",
  },
  {
    id: 212,
    rewrite: "CH",
    baslik: "Switzerland",
    alankodu: "41",
  },
  {
    id: 213,
    rewrite: "SY",
    baslik: "Syria",
    alankodu: "963",
  },
  {
    id: 214,
    rewrite: "TW",
    baslik: "Taiwan",
    alankodu: "886",
  },
  {
    id: 215,
    rewrite: "TJ",
    baslik: "Tajikistan",
    alankodu: "992",
  },
  {
    id: 216,
    rewrite: "TZ",
    baslik: "Tanzania",
    alankodu: "255",
  },
  {
    id: 217,
    rewrite: "TH",
    baslik: "Thailand",
    alankodu: "66",
  },
  {
    id: 218,
    rewrite: "TG",
    baslik: "Togo",
    alankodu: "228",
  },
  {
    id: 219,
    rewrite: "TK",
    baslik: "Tokelau",
    alankodu: "690",
  },
  {
    id: 220,
    rewrite: "TO",
    baslik: "Tonga",
    alankodu: "676",
  },
  {
    id: 221,
    rewrite: "TT",
    baslik: "Trinidad And Tobago",
    alankodu: "1868",
  },
  {
    id: 222,
    rewrite: "TN",
    baslik: "Tunisia",
    alankodu: "216",
  },
  {
    id: 223,
    rewrite: "TR",
    baslik: "Türkiye",
    alankodu: "90",
  },
  {
    id: 224,
    rewrite: "TM",
    baslik: "Turkmenistan",
    alankodu: "7370",
  },
  {
    id: 225,
    rewrite: "TC",
    baslik: "Turks And Caicos Islands",
    alankodu: "1649",
  },
  {
    id: 226,
    rewrite: "TV",
    baslik: "Tuvalu",
    alankodu: "688",
  },
  {
    id: 227,
    rewrite: "UG",
    baslik: "Uganda",
    alankodu: "256",
  },
  {
    id: 228,
    rewrite: "UA",
    baslik: "Ukraine",
    alankodu: "380",
  },
  {
    id: 229,
    rewrite: "AE",
    baslik: "United Arab Emirates",
    alankodu: "971",
  },
  {
    id: 230,
    rewrite: "GB",
    baslik: "United Kingdom",
    alankodu: "44",
  },
  {
    id: 231,
    rewrite: "US",
    baslik: "United States",
    alankodu: "1",
  },
  {
    id: 232,
    rewrite: "UM",
    baslik: "United States Minor Outlying Islands",
    alankodu: "1",
  },
  {
    id: 233,
    rewrite: "UY",
    baslik: "Uruguay",
    alankodu: "598",
  },
  {
    id: 234,
    rewrite: "UZ",
    baslik: "Uzbekistan",
    alankodu: "998",
  },
  {
    id: 235,
    rewrite: "VU",
    baslik: "Vanuatu",
    alankodu: "678",
  },
  {
    id: 236,
    rewrite: "VA",
    baslik: "Vatican City State (Holy See)",
    alankodu: "39",
  },
  {
    id: 237,
    rewrite: "VE",
    baslik: "Venezuela",
    alankodu: "58",
  },
  {
    id: 238,
    rewrite: "VN",
    baslik: "Vietnam",
    alankodu: "84",
  },
  {
    id: 239,
    rewrite: "VG",
    baslik: "Virgin Islands (British)",
    alankodu: "1284",
  },
  {
    id: 240,
    rewrite: "VI",
    baslik: "Virgin Islands (US)",
    alankodu: "1340",
  },
  {
    id: 241,
    rewrite: "WF",
    baslik: "Wallis And Futuna Islands",
    alankodu: "681",
  },
  {
    id: 242,
    rewrite: "EH",
    baslik: "Western Sahara",
    alankodu: "212",
  },
  {
    id: 243,
    rewrite: "YE",
    baslik: "Yemen",
    alankodu: "967",
  },
  {
    id: 244,
    rewrite: "YU",
    baslik: "Yugoslavia",
    alankodu: "38",
  },
  {
    id: 245,
    rewrite: "ZM",
    baslik: "Zambia",
    alankodu: "260",
  },
  {
    id: 246,
    rewrite: "ZW",
    baslik: "Zimbabwe",
    alankodu: "263",
  },
];

export default countries;
